add macOS Disable System Updates TTP
facebookincubator/ForgeArmory pull request #34
Opened 2023-08-21 18:26 UTC by VVX7

# Proposed Changes

macOS Disable System Updates TTP + readme

I didn't see an example of a TTP that requires admin permissions so I've added one. Currently this TTP assumes the user is a member of sudoers and prompts for their password at run time. Wondering if you had plans to handle this differently.

## Related Issue(s)

n/a

## Testing

Executed on local machine to confirm effects and cleanup.

## Documentation

Included in README.md

## Screenshots/GIFs (optional)

n/a

## Checklist

- [ x ] Ran `mage runprecommit` locally and fixed any issues that arose.
- [ x ] Curated your commit(s) so they are legible and easy to read and understand.
- [ x ] 🚀

2023-08-21 19:24 UTC, VVX7 commented
huh local precommit didn't throw an error on the trailing whitespace. gonna write a few more ttps just to go through the motions. will pull a fresh copy to see if it happens again.

2023-08-22 00:22 UTC, l50 commented
> huh local precommit didn't throw an error on the trailing whitespace. gonna write a few more ttps just to go through the motions. will pull a fresh copy to see if it happens again.

That's odd. What version of pre-commit are you running? 

We also provide a [dev container](https://github.com/facebookincubator/TTPForge/tree/main/.devcontainer/bash), which will be quite representative of what is happening in our github actions.

2023-08-22 00:40 UTC, l50 requested changes
Let's make sure you get credit in badge form for your awesome submission :)

Also, if you have any other info around the pre-commit issue you ran into (see comment for more info), please LMK so I can try and replicate.

2023-08-22 00:46 UTC, l50 commented
This is so awesome, thank you so much for another TTP!!\

2023-08-22 22:24 UTC, VVX7 commented on ttps/defense-evasion/macos/disable-system-updates/README.md
> +![Meta TTP](https://img.shields.io/badge/Meta_TTP-blue)
Yep! Good idea to differentiate community TTPs from those authored by your team.

2023-08-23 22:12 UTC, l50 approved these changes

2023-08-23 22:12 UTC, merged